package MicroservicesArchitectureLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EnvironmentType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnvironmentType() {
    super(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb122L, "EnvironmentType", "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227682");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Development_0 = new EnumerationDescriptor.MemberDescriptor("Development", "Development", 0x2e2e087c4bdeb123L, "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227683");
  private final EnumerationDescriptor.MemberDescriptor myMember_Test_0 = new EnumerationDescriptor.MemberDescriptor("Test", "Test", 0x2e2e087c4bdeb124L, "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227684");
  private final EnumerationDescriptor.MemberDescriptor myMember_UAT_0 = new EnumerationDescriptor.MemberDescriptor("UAT", "UAT", 0x2e2e087c4bdeb127L, "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227687");
  private final EnumerationDescriptor.MemberDescriptor myMember_Demo_0 = new EnumerationDescriptor.MemberDescriptor("Demo", "Demo", 0x2e2e087c4bdeb12bL, "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227691");
  private final EnumerationDescriptor.MemberDescriptor myMember_Production_0 = new EnumerationDescriptor.MemberDescriptor("Production", "Production", 0x2e2e087c4bdeb130L, "r:48771403-405a-41ee-a755-08578f66c616(MicroservicesArchitectureLanguage.structure)/3327606504615227696");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb122L, 0x2e2e087c4bdeb123L, 0x2e2e087c4bdeb124L, 0x2e2e087c4bdeb127L, 0x2e2e087c4bdeb12bL, 0x2e2e087c4bdeb130L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Development_0, myMember_Test_0, myMember_UAT_0, myMember_Demo_0, myMember_Production_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Production_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Development":
        return myMember_Development_0;
      case "Test":
        return myMember_Test_0;
      case "UAT":
        return myMember_UAT_0;
      case "Demo":
        return myMember_Demo_0;
      case "Production":
        return myMember_Production_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
