/**
 * generated by Xtext 2.25.0
 */
package org.xtext.microservices.mydsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
