package MicroservicesArchitectureLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Communicates_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Container_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Environment_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Microservice_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ServerNode_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new VirtualMachine_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x401f62f44cfb5204L), MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb0d7L), MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb11bL), MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e21840e21edea85L), MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e21840e21edea7cL), MetaIdFactory.conceptId(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e21840e21edea82L)).seal();
}
