<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="refinedMicroservices" nsURI="http://www.example.org/refinedMicroservices"
    nsPrefix="refinedMicroservices">
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//EnvironmentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RAM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Processor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Disk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dockers" upperBound="-1"
        eType="#//Docker" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Docker" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IPv4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Microservice" eType="#//Microservice"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Microservice" eSuperTypes="#//Entity #//DataTransferObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CommunicationType" eType="#//MicroserviceCommunicationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Health" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTransferObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="JsonString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MicroserviceCommunicationType">
    <eLiterals name="RPC"/>
    <eLiterals name="REST" value="1"/>
    <eLiterals name="PubSub" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentType">
    <eLiterals name="Development"/>
    <eLiterals name="Test" value="1"/>
    <eLiterals name="UAT" value="2"/>
    <eLiterals name="Demo" value="3"/>
    <eLiterals name="Production" value="4"/>
  </eClassifiers>
</ecore:EPackage>
