package MicroserviceArchitectureLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_VMType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_VMType() {
    super(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb141L, "VMType", "r:48771403-405a-41ee-a755-08578f66c616(MicroserviceArchitectureLanguage.structure)/3327606504615227713");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Linux_0 = new EnumerationDescriptor.MemberDescriptor("Linux", "Linux", 0x2e2e087c4bdeb142L, "r:48771403-405a-41ee-a755-08578f66c616(MicroserviceArchitectureLanguage.structure)/3327606504615227714");
  private final EnumerationDescriptor.MemberDescriptor myMember_RedHat_0 = new EnumerationDescriptor.MemberDescriptor("RedHat", "RedHat", 0x2e2e087c4bdeb143L, "r:48771403-405a-41ee-a755-08578f66c616(MicroserviceArchitectureLanguage.structure)/3327606504615227715");
  private final EnumerationDescriptor.MemberDescriptor myMember_Windows_0 = new EnumerationDescriptor.MemberDescriptor("Windows", "Windows", 0x2e2e087c4bdeb146L, "r:48771403-405a-41ee-a755-08578f66c616(MicroserviceArchitectureLanguage.structure)/3327606504615227718");
  private final EnumerationDescriptor.MemberDescriptor myMember_CentOS_0 = new EnumerationDescriptor.MemberDescriptor("CentOS", "CentOS", 0x2e2e087c4bdeb14aL, "r:48771403-405a-41ee-a755-08578f66c616(MicroserviceArchitectureLanguage.structure)/3327606504615227722");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3d827bac02154a87L, 0x8b1c1ab047e79a3bL, 0x2e2e087c4bdeb141L, 0x2e2e087c4bdeb142L, 0x2e2e087c4bdeb143L, 0x2e2e087c4bdeb146L, 0x2e2e087c4bdeb14aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Linux_0, myMember_RedHat_0, myMember_Windows_0, myMember_CentOS_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Linux_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Linux":
        return myMember_Linux_0;
      case "RedHat":
        return myMember_RedHat_0;
      case "Windows":
        return myMember_Windows_0;
      case "CentOS":
        return myMember_CentOS_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
