/**
 * generated by Xtext 2.25.0
 */
package org.xtext.microservices.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.EnvironmentModel#getEnvironment <em>Environment</em>}</li>
 * </ul>
 *
 * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironmentModel()
 * @model
 * @generated
 */
public interface EnvironmentModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Environment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment</em>' containment reference.
   * @see #setEnvironment(Environment)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironmentModel_Environment()
   * @model containment="true"
   * @generated
   */
  Environment getEnvironment();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentModel#getEnvironment <em>Environment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Environment</em>' containment reference.
   * @see #getEnvironment()
   * @generated
   */
  void setEnvironment(Environment value);

} // EnvironmentModel
