/**
 * generated by Xtext 2.25.0
 */
package org.xtext.microservices.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.Environment#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.Environment#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.Environment#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.Environment#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironment()
 * @model
 * @generated
 */
public interface Environment extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironment_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.Environment#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironment_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.Environment#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.microservices.mydsl.myDsl.EnvironmentType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentType
   * @see #setType(EnvironmentType)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironment_Type()
   * @model
   * @generated
   */
  EnvironmentType getType();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.Environment#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentType
   * @see #getType()
   * @generated
   */
  void setType(EnvironmentType value);

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.microservices.mydsl.myDsl.ServerNode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference list.
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getEnvironment_Nodes()
   * @model containment="true"
   * @generated
   */
  EList<ServerNode> getNodes();

} // Environment
