/**
 * generated by Xtext 2.25.0
 */
package org.xtext.microservices.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.microservices.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/microservices/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.EnvironmentModelImpl <em>Environment Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.EnvironmentModelImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironmentModel()
   * @generated
   */
  int ENVIRONMENT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Environment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_MODEL__ENVIRONMENT = 0;

  /**
   * The number of structural features of the '<em>Environment Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.EnvironmentImpl <em>Environment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.EnvironmentImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironment()
   * @generated
   */
  int ENVIRONMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__ID = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__TYPE = 2;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__NODES = 3;

  /**
   * The number of structural features of the '<em>Environment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.ServerNodeImpl <em>Server Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.ServerNodeImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getServerNode()
   * @generated
   */
  int SERVER_NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_NODE__ID = 1;

  /**
   * The feature id for the '<em><b>Vms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_NODE__VMS = 2;

  /**
   * The number of structural features of the '<em>Server Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_NODE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.VirtualMachineImpl <em>Virtual Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.VirtualMachineImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getVirtualMachine()
   * @generated
   */
  int VIRTUAL_MACHINE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIRTUAL_MACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIRTUAL_MACHINE__ID = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIRTUAL_MACHINE__TYPE = 2;

  /**
   * The feature id for the '<em><b>Dockers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIRTUAL_MACHINE__DOCKERS = 3;

  /**
   * The number of structural features of the '<em>Virtual Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIRTUAL_MACHINE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.ContainerImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__ID = 1;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__PORT = 2;

  /**
   * The feature id for the '<em><b>Microservice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__MICROSERVICE = 3;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.impl.MicroserviceImpl <em>Microservice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.impl.MicroserviceImpl
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getMicroservice()
   * @generated
   */
  int MICROSERVICE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MICROSERVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MICROSERVICE__ID = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MICROSERVICE__TYPE = 2;

  /**
   * The number of structural features of the '<em>Microservice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MICROSERVICE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentType <em>Environment Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentType
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironmentType()
   * @generated
   */
  int ENVIRONMENT_TYPE = 6;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.VMType <em>VM Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.VMType
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getVMType()
   * @generated
   */
  int VM_TYPE = 7;

  /**
   * The meta object id for the '{@link org.xtext.microservices.mydsl.myDsl.MicroserviceType <em>Microservice Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.microservices.mydsl.myDsl.MicroserviceType
   * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getMicroserviceType()
   * @generated
   */
  int MICROSERVICE_TYPE = 8;


  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentModel <em>Environment Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Environment Model</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentModel
   * @generated
   */
  EClass getEnvironmentModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentModel#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Environment</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentModel#getEnvironment()
   * @see #getEnvironmentModel()
   * @generated
   */
  EReference getEnvironmentModel_Environment();

  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.Environment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Environment</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Environment
   * @generated
   */
  EClass getEnvironment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Environment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Environment#getName()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Environment#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Environment#getId()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Environment#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Environment#getType()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.microservices.mydsl.myDsl.Environment#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Environment#getNodes()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Nodes();

  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.ServerNode <em>Server Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server Node</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.ServerNode
   * @generated
   */
  EClass getServerNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.ServerNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.ServerNode#getName()
   * @see #getServerNode()
   * @generated
   */
  EAttribute getServerNode_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.ServerNode#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.ServerNode#getId()
   * @see #getServerNode()
   * @generated
   */
  EAttribute getServerNode_Id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.microservices.mydsl.myDsl.ServerNode#getVms <em>Vms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vms</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.ServerNode#getVms()
   * @see #getServerNode()
   * @generated
   */
  EReference getServerNode_Vms();

  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine <em>Virtual Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Virtual Machine</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VirtualMachine
   * @generated
   */
  EClass getVirtualMachine();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VirtualMachine#getName()
   * @see #getVirtualMachine()
   * @generated
   */
  EAttribute getVirtualMachine_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VirtualMachine#getId()
   * @see #getVirtualMachine()
   * @generated
   */
  EAttribute getVirtualMachine_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VirtualMachine#getType()
   * @see #getVirtualMachine()
   * @generated
   */
  EAttribute getVirtualMachine_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getDockers <em>Dockers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dockers</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VirtualMachine#getDockers()
   * @see #getVirtualMachine()
   * @generated
   */
  EReference getVirtualMachine_Dockers();

  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Container#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Container#getName()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Container#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Container#getId()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Container#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Container#getPort()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_Port();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.microservices.mydsl.myDsl.Container#getMicroservice <em>Microservice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Microservice</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Container#getMicroservice()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Microservice();

  /**
   * Returns the meta object for class '{@link org.xtext.microservices.mydsl.myDsl.Microservice <em>Microservice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Microservice</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Microservice
   * @generated
   */
  EClass getMicroservice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Microservice#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Microservice#getName()
   * @see #getMicroservice()
   * @generated
   */
  EAttribute getMicroservice_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Microservice#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Microservice#getId()
   * @see #getMicroservice()
   * @generated
   */
  EAttribute getMicroservice_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.microservices.mydsl.myDsl.Microservice#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.Microservice#getType()
   * @see #getMicroservice()
   * @generated
   */
  EAttribute getMicroservice_Type();

  /**
   * Returns the meta object for enum '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentType <em>Environment Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Environment Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.EnvironmentType
   * @generated
   */
  EEnum getEnvironmentType();

  /**
   * Returns the meta object for enum '{@link org.xtext.microservices.mydsl.myDsl.VMType <em>VM Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>VM Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.VMType
   * @generated
   */
  EEnum getVMType();

  /**
   * Returns the meta object for enum '{@link org.xtext.microservices.mydsl.myDsl.MicroserviceType <em>Microservice Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Microservice Type</em>'.
   * @see org.xtext.microservices.mydsl.myDsl.MicroserviceType
   * @generated
   */
  EEnum getMicroserviceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.EnvironmentModelImpl <em>Environment Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.EnvironmentModelImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironmentModel()
     * @generated
     */
    EClass ENVIRONMENT_MODEL = eINSTANCE.getEnvironmentModel();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT_MODEL__ENVIRONMENT = eINSTANCE.getEnvironmentModel_Environment();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.EnvironmentImpl <em>Environment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.EnvironmentImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironment()
     * @generated
     */
    EClass ENVIRONMENT = eINSTANCE.getEnvironment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__NAME = eINSTANCE.getEnvironment_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__ID = eINSTANCE.getEnvironment_Id();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__TYPE = eINSTANCE.getEnvironment_Type();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__NODES = eINSTANCE.getEnvironment_Nodes();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.ServerNodeImpl <em>Server Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.ServerNodeImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getServerNode()
     * @generated
     */
    EClass SERVER_NODE = eINSTANCE.getServerNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_NODE__NAME = eINSTANCE.getServerNode_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_NODE__ID = eINSTANCE.getServerNode_Id();

    /**
     * The meta object literal for the '<em><b>Vms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER_NODE__VMS = eINSTANCE.getServerNode_Vms();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.VirtualMachineImpl <em>Virtual Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.VirtualMachineImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getVirtualMachine()
     * @generated
     */
    EClass VIRTUAL_MACHINE = eINSTANCE.getVirtualMachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIRTUAL_MACHINE__NAME = eINSTANCE.getVirtualMachine_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIRTUAL_MACHINE__ID = eINSTANCE.getVirtualMachine_Id();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIRTUAL_MACHINE__TYPE = eINSTANCE.getVirtualMachine_Type();

    /**
     * The meta object literal for the '<em><b>Dockers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIRTUAL_MACHINE__DOCKERS = eINSTANCE.getVirtualMachine_Dockers();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.ContainerImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__NAME = eINSTANCE.getContainer_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__ID = eINSTANCE.getContainer_Id();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__PORT = eINSTANCE.getContainer_Port();

    /**
     * The meta object literal for the '<em><b>Microservice</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__MICROSERVICE = eINSTANCE.getContainer_Microservice();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.impl.MicroserviceImpl <em>Microservice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.impl.MicroserviceImpl
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getMicroservice()
     * @generated
     */
    EClass MICROSERVICE = eINSTANCE.getMicroservice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MICROSERVICE__NAME = eINSTANCE.getMicroservice_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MICROSERVICE__ID = eINSTANCE.getMicroservice_Id();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MICROSERVICE__TYPE = eINSTANCE.getMicroservice_Type();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.EnvironmentType <em>Environment Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.EnvironmentType
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getEnvironmentType()
     * @generated
     */
    EEnum ENVIRONMENT_TYPE = eINSTANCE.getEnvironmentType();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.VMType <em>VM Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.VMType
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getVMType()
     * @generated
     */
    EEnum VM_TYPE = eINSTANCE.getVMType();

    /**
     * The meta object literal for the '{@link org.xtext.microservices.mydsl.myDsl.MicroserviceType <em>Microservice Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.microservices.mydsl.myDsl.MicroserviceType
     * @see org.xtext.microservices.mydsl.myDsl.impl.MyDslPackageImpl#getMicroserviceType()
     * @generated
     */
    EEnum MICROSERVICE_TYPE = eINSTANCE.getMicroserviceType();

  }

} //MyDslPackage
