/**
 * generated by Xtext 2.25.0
 */
package org.xtext.microservices.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Virtual Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getDockers <em>Dockers</em>}</li>
 * </ul>
 *
 * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getVirtualMachine()
 * @model
 * @generated
 */
public interface VirtualMachine extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getVirtualMachine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getVirtualMachine_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.microservices.mydsl.myDsl.VMType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.microservices.mydsl.myDsl.VMType
   * @see #setType(VMType)
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getVirtualMachine_Type()
   * @model
   * @generated
   */
  VMType getType();

  /**
   * Sets the value of the '{@link org.xtext.microservices.mydsl.myDsl.VirtualMachine#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.microservices.mydsl.myDsl.VMType
   * @see #getType()
   * @generated
   */
  void setType(VMType value);

  /**
   * Returns the value of the '<em><b>Dockers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.microservices.mydsl.myDsl.Container}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dockers</em>' containment reference list.
   * @see org.xtext.microservices.mydsl.myDsl.MyDslPackage#getVirtualMachine_Dockers()
   * @model containment="true"
   * @generated
   */
  EList<Container> getDockers();

} // VirtualMachine
